use std::fs::{self, File};
use std::io::Write;
use std::path::PathBuf;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;
use parking_lot::Mutex;
use serde::{Deserialize, Serialize};

/// Current on-disk schema version. Bump when the layout/field shape changes so
/// `migrate_workspace` can upgrade old files instead of failing to parse them.
const WORKSPACE_SCHEMA_VERSION: u32 = 1;

#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(default)]
pub struct WorkspaceData {
    pub id: String,
    pub name: String,
    pub layout: serde_json::Value,
    pub created_at: u64,
    pub updated_at: u64,
    /// Schema version for forward/backward compatibility (audit improvement:
    /// old files without the field default to 1 and are migrated in place).
    pub version: u32,
    /// Optional per-workspace settings overrides (customization audit C12):
    /// theme/font/shell/cwd/opacity scoped to this workspace. Opaque JSON so
    /// the frontend owns the shape; old files without the field default to
    /// None and fall through to the global settings.
    pub overrides: Option<serde_json::Value>,
    /// Optional emoji badge (customization audit C23).
    pub emoji: Option<String>,
    /// Soft-delete flag (customization audit C23).
    pub archived: Option<bool>,
}

impl Default for WorkspaceData {
    fn default() -> Self {
        Self {
            id: String::new(),
            name: String::new(),
            layout: serde_json::Value::Null,
            created_at: 0,
            updated_at: 0,
            version: WORKSPACE_SCHEMA_VERSION,
            overrides: None,
            emoji: None,
            archived: None,
        }
    }
}

impl WorkspaceData {
    /// Upgrade an older workspace file to the current schema. Today the layout
    /// shape is unchanged since v1, so this only stamps the version — the hook
    /// is where future migrations (e.g. v1 → v2 field renames) will live.
    pub fn migrate(&mut self) {
        if self.version < WORKSPACE_SCHEMA_VERSION {
            // v1 → current: no layout changes needed yet.
            self.version = WORKSPACE_SCHEMA_VERSION;
        }
    }
}

/// Workspace IDs are interpolated into storage paths (`{id}.json`), so only
/// allow a conservative, path-safe charset — defense in depth even though IDs
/// are generated by the app itself (audit: IDs were used unsanitized).
fn is_safe_id(id: &str) -> bool {
    !id.is_empty()
        && id.len() <= 128
        && id
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
}

#[derive(Clone)]
pub struct WorkspaceManager {
    storage_dir: PathBuf,
    /// Serializes concurrent saves so a fire-and-forget switch save can never
    /// interleave with the debounced autosave of the same workspace (rapid
    /// workspace switching writes from multiple code paths).
    write_lock: Arc<Mutex<()>>,
    /// Uniqueness for temp file names — two saves of the SAME workspace must
    /// never share a `.tmp` path or the second `File::create` truncates the
    /// first before its rename.
    temp_counter: Arc<AtomicU64>,
}

impl Default for WorkspaceManager {
    fn default() -> Self {
        Self::new()
    }
}

impl WorkspaceManager {
    pub fn new() -> Self {
        let storage_dir = crate::utils::paths::get_workspaces_dir();

        if !storage_dir.exists() {
            let _ = fs::create_dir_all(&storage_dir);
        }

        Self::with_storage_dir(storage_dir)
    }

    /// Construct a manager rooted at an explicit directory (used by tests).
    pub fn with_storage_dir(storage_dir: PathBuf) -> Self {
        Self {
            storage_dir,
            write_lock: Arc::new(Mutex::new(())),
            temp_counter: Arc::new(AtomicU64::new(0)),
        }
    }

    /// Atomically save workspace to JSON using temp file + rename (NFR-014).
    /// Serialized per-manager and given a UNIQUE temp name per write so
    /// concurrent saves of the same workspace (rapid switching + autosave)
    /// can't clobber each other's temp file; `sync_all` flushes to disk before
    /// the rename so a crash mid-save never leaves a truncated workspace file.
    pub fn save_workspace(&self, workspace: &WorkspaceData) -> Result<(), String> {
        if !is_safe_id(&workspace.id) {
            return Err(format!("Refusing to save workspace with unsafe id: {:?}", workspace.id));
        }
        let _guard = self.write_lock.lock();

        let file_path = self.storage_dir.join(format!("{}.json", workspace.id));
        let unique = self.temp_counter.fetch_add(1, Ordering::Relaxed);
        let temp_path = self.storage_dir.join(format!("{}.tmp.{}", workspace.id, unique));

        let json_data = serde_json::to_string_pretty(workspace)
            .map_err(|e| format!("Failed to serialize workspace: {}", e))?;

        let mut temp_file = File::create(&temp_path)
            .map_err(|e| format!("Failed to create temp file: {}", e))?;

        temp_file
            .write_all(json_data.as_bytes())
            .map_err(|e| format!("Failed to write workspace data: {}", e))?;

        temp_file
            .flush()
            .map_err(|e| format!("Failed to flush temp file: {}", e))?;
        temp_file
            .sync_all()
            .map_err(|e| format!("Failed to sync temp file: {}", e))?;
        drop(temp_file); // Windows requires the file closed before rename

        fs::rename(&temp_path, &file_path)
            .map_err(|e| format!("Failed to rename temp workspace file: {}", e))?;

        Ok(())
    }

    /// Load workspace by ID
    pub fn load_workspace(&self, id: &str) -> Result<WorkspaceData, String> {
        if !is_safe_id(id) {
            return Err(format!("Refusing to load workspace with unsafe id: {:?}", id));
        }
        let file_path = self.storage_dir.join(format!("{}.json", id));
        if !file_path.exists() {
            return Err(format!("Workspace {} not found", id));
        }

        let content = fs::read_to_string(&file_path)
            .map_err(|e| format!("Failed to read workspace file: {}", e))?;

        let mut workspace: WorkspaceData = serde_json::from_str(&content)
            .map_err(|e| format!("Failed to parse workspace JSON: {}", e))?;

        // Audit improvement: upgrade older files to the current schema.
        workspace.migrate();

        Ok(workspace)
    }

    /// List all persisted workspaces
    pub fn list_workspaces(&self) -> Result<Vec<WorkspaceData>, String> {
        let mut result = Vec::new();
        if !self.storage_dir.exists() {
            return Ok(result);
        }

        let entries = fs::read_dir(&self.storage_dir)
            .map_err(|e| format!("Failed to read workspace directory: {}", e))?;

        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) == Some("json") {
                if let Ok(content) = fs::read_to_string(&path) {
                    if let Ok(mut ws) = serde_json::from_str::<WorkspaceData>(&content) {
                        // Audit improvement: migrate old files before returning.
                        ws.migrate();
                        result.push(ws);
                    }
                }
            }
        }

        result.sort_by_key(|b| std::cmp::Reverse(b.updated_at));
        Ok(result)
    }

    /// Delete workspace by ID
    pub fn delete_workspace(&self, id: &str) -> Result<(), String> {
        if !is_safe_id(id) {
            return Err(format!("Refusing to delete workspace with unsafe id: {:?}", id));
        }
        let file_path = self.storage_dir.join(format!("{}.json", id));
        if file_path.exists() {
            fs::remove_file(file_path)
                .map_err(|e| format!("Failed to delete workspace file: {}", e))?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_workspace_atomic_save_load_delete() {
        let dir = tempdir().unwrap();
        let manager = WorkspaceManager::with_storage_dir(dir.path().to_path_buf());

        let ws = WorkspaceData {
            id: "ws-test-1".to_string(),
            name: "Test Workspace".to_string(),
            layout: serde_json::json!({"type": "terminal"}),
            created_at: 1000,
            updated_at: 1000,
            version: 1,
            overrides: Some(serde_json::json!({"themeName": "nord"})),
            emoji: Some("🚀".to_string()),
            archived: Some(false),
        };

        assert!(manager.save_workspace(&ws).is_ok());

        let loaded = manager.load_workspace("ws-test-1").unwrap();
        assert_eq!(loaded.name, "Test Workspace");
        assert_eq!(loaded.version, 1);

        let list = manager.list_workspaces().unwrap();
        assert_eq!(list.len(), 1);

        assert!(manager.delete_workspace("ws-test-1").is_ok());
        assert!(manager.load_workspace("ws-test-1").is_err());
    }

    #[test]
    fn test_concurrent_saves_never_clobber_each_other() {
        let dir = tempdir().unwrap();
        let manager = WorkspaceManager::with_storage_dir(dir.path().to_path_buf());

        // Fire many saves of the SAME workspace in parallel (mimics rapid
        // workspace switching + debounced autosave racing). Every save uses a
        // unique temp name + the write lock, so none can truncate another's
        // temp file and the final file must be one complete, valid JSON.
        let manager = std::sync::Arc::new(manager);
        let handles: Vec<_> = (0..32)
            .map(|i| {
                let manager = std::sync::Arc::clone(&manager);
                std::thread::spawn(move || {
                    let ws = WorkspaceData {
                        id: "ws-race".to_string(),
                        name: format!("Race {i}"),
                        layout: serde_json::json!({ "type": "terminal", "id": format!("term-{i}") }),
                        created_at: 0,
                        updated_at: i as u64,
                        version: 1,
                        overrides: None,
                        emoji: None,
                        archived: None,
                    };
                    manager.save_workspace(&ws).unwrap();
                })
            })
            .collect();
        for h in handles {
            h.join().unwrap();
        }

        // No temp files may be left behind, and the final workspace file must
        // parse as complete JSON (no torn/truncated writes). Temp names are
        // `{id}.tmp.{N}` — check by FILE NAME (the extension is the counter,
        // so extension == "tmp" would never match and the check would be
        // vacuous).
        let leftovers: Vec<_> = fs::read_dir(dir.path())
            .unwrap()
            .filter_map(|e| e.ok())
            .filter(|e| e.file_name().to_string_lossy().contains(".tmp."))
            .collect();
        assert!(leftovers.is_empty(), "temp files left behind: {:?}", leftovers.len());

        let loaded = manager.load_workspace("ws-race").unwrap();
        assert!(loaded.name.starts_with("Race "));
        assert!(loaded.layout.is_object());
    }

    #[test]
    fn test_rejects_unsafe_ids() {
        // Audit: IDs are interpolated into storage paths — path traversal and
        // unsupported chars must be refused on ALL operations.
        let dir = tempdir().unwrap();
        let manager = WorkspaceManager::with_storage_dir(dir.path().to_path_buf());

        for bad in ["../escape", "a/b", "a\\b", "a b", "a:0", ""] {
            let ws = WorkspaceData {
                id: bad.to_string(),
                name: "x".to_string(),
                layout: serde_json::json!({}),
                created_at: 0,
                updated_at: 0,
                version: 1,
                overrides: None,
                emoji: None,
                archived: None,
            };
            assert!(manager.save_workspace(&ws).is_err(), "save should refuse {bad:?}");
            assert!(manager.load_workspace(bad).is_err(), "load should refuse {bad:?}");
            assert!(manager.delete_workspace(bad).is_err(), "delete should refuse {bad:?}");
        }

        // A well-formed generated id (ws- + timestamp) passes.
        let ok = WorkspaceData {
            id: "ws-1720000000000".to_string(),
            name: "x".to_string(),
            layout: serde_json::json!({}),
            created_at: 0,
            updated_at: 0,
            version: 1,
            overrides: None,
            emoji: None,
            archived: None,
        };
        assert!(manager.save_workspace(&ok).is_ok());
    }

    #[test]
    fn test_save_leaves_no_temp_files() {
        let dir = tempdir().unwrap();
        let manager = WorkspaceManager::with_storage_dir(dir.path().to_path_buf());

        let ws = WorkspaceData {
            id: "ws-clean".to_string(),
            name: "Clean".to_string(),
            layout: serde_json::json!({ "type": "terminal" }),
            created_at: 0,
            updated_at: 0,
            version: 1,
            overrides: None,
            emoji: None,
            archived: None,
        };
        manager.save_workspace(&ws).unwrap();

        // Only the real workspace file exists — no stray temp files. Filter to
        // *.json so platform artifacts (e.g. .DS_Store) can't flake the test.
        let files: Vec<String> = fs::read_dir(dir.path())
            .unwrap()
            .filter_map(|e| e.ok())
            .map(|e| e.file_name().to_string_lossy().to_string())
            .filter(|n| n.ends_with(".json"))
            .collect();
        assert_eq!(files, vec!["ws-clean.json"]);
    }
}
