export interface DemoLayoutPreset {
  id: string;
  name: string;
  badge: string;
  category: 'solo' | 'duo' | 'trio' | 'quad' | 'hexa' | 'octa' | 'matrix';
  description: string;
  paneCount: number;
  shortcut: string;
  tags: string[];
  recommendedRatio?: 'equal' | 'golden' | 'hero-sidebar';
  previewWireframe: { id: number; label: string; flex: string }[];
}

export const DEMO_LAYOUT_PRESETS: DemoLayoutPreset[] = [
  {
    id: 'solo',
    name: '1-Pane Solo',
    badge: 'FOCUS',
    category: 'solo',
    description: 'Single full-bleed distraction-free terminal.',
    paneCount: 1,
    shortcut: '1',
    tags: ['Solo', 'Focus', 'Minimal'],
    recommendedRatio: 'equal',
    previewWireframe: [
      { id: 1, label: '#01 Primary', flex: 'h-full w-full' },
    ],
  },
  {
    id: '1x2',
    name: '2-Pane Horizontal (2H)',
    badge: 'PAIRING',
    category: 'duo',
    description: 'Classic side-by-side split for coding & tests.',
    paneCount: 2,
    shortcut: '2',
    tags: ['2H', 'Editor', 'Runner'],
    recommendedRatio: 'equal',
    previewWireframe: [
      { id: 1, label: '#01 Editor', flex: 'h-full w-1/2' },
      { id: 2, label: '#02 Tests', flex: 'h-full w-1/2' },
    ],
  },
  {
    id: '2-vertical',
    name: '2-Pane Vertical (2V)',
    badge: 'STACK',
    category: 'duo',
    description: 'Top/bottom horizontal split for long log streams.',
    paneCount: 2,
    shortcut: 'Alt+2',
    tags: ['2V', 'Logs', 'Server'],
    recommendedRatio: 'equal',
    previewWireframe: [
      { id: 1, label: '#01 Work', flex: 'h-1/2 w-full' },
      { id: 2, label: '#02 Tail', flex: 'h-1/2 w-full' },
    ],
  },
  {
    id: '3-t-top',
    name: '3-Pane T-Split Top',
    badge: 'SUPERVISOR',
    category: 'trio',
    description: 'Wide master pane above two worker sidecars.',
    paneCount: 3,
    shortcut: '3',
    tags: ['Supervisor', 'Multi-Agent', 'T-Top'],
    recommendedRatio: 'golden',
    previewWireframe: [
      { id: 1, label: '#01 Master', flex: 'h-1/2 w-full' },
      { id: 2, label: '#02 Worker A', flex: 'h-1/2 w-1/2' },
      { id: 3, label: '#03 Worker B', flex: 'h-1/2 w-1/2' },
    ],
  },
  {
    id: '3-t-bottom',
    name: '3-Pane T-Split Bottom',
    badge: 'DEVOPS',
    category: 'trio',
    description: 'Dual work panes on top + full-width telemetry below.',
    paneCount: 3,
    shortcut: 'Alt+3',
    tags: ['DevOps', 'Telemetry', 'T-Bottom'],
    recommendedRatio: 'golden',
    previewWireframe: [
      { id: 1, label: '#01 Work A', flex: 'h-1/2 w-1/2' },
      { id: 2, label: '#02 Work B', flex: 'h-1/2 w-1/2' },
      { id: 3, label: '#03 Telemetry', flex: 'h-1/2 w-full' },
    ],
  },
  {
    id: '3-columns',
    name: '3-Columns',
    badge: 'TILING',
    category: 'trio',
    description: 'Three parallel vertical columns for tri-stream auditing.',
    paneCount: 3,
    shortcut: 'Ctrl+3',
    tags: ['Columns', 'Tiling', 'Review'],
    recommendedRatio: 'equal',
    previewWireframe: [
      { id: 1, label: '#01 Col 1', flex: 'h-full w-1/3' },
      { id: 2, label: '#02 Col 2', flex: 'h-full w-1/3' },
      { id: 3, label: '#03 Col 3', flex: 'h-full w-1/3' },
    ],
  },
  {
    id: '2x2',
    name: '4-Quad 2×2 Matrix',
    badge: 'BALANCED',
    category: 'quad',
    description: '4 balanced terminal quadrants for full-stack autonomous agent fleets.',
    paneCount: 4,
    shortcut: '4',
    tags: ['Quad', '2x2', 'Swarm'],
    recommendedRatio: 'equal',
    previewWireframe: [
      { id: 1, label: '#01 Claude', flex: 'h-1/2 w-1/2' },
      { id: 2, label: '#02 Aider', flex: 'h-1/2 w-1/2' },
      { id: 3, label: '#03 Ollama', flex: 'h-1/2 w-1/2' },
      { id: 4, label: '#04 Dev', flex: 'h-1/2 w-1/2' },
    ],
  },
  {
    id: 'hero-1-3',
    name: '4-Master Detail 1+3',
    badge: 'FLAGSHIP',
    category: 'quad',
    description: '1 commanding wide primary terminal with 3 stacked side-monitor panes.',
    paneCount: 4,
    shortcut: 'Alt+4',
    tags: ['IDE Style', 'Hierarchy', '1+3'],
    recommendedRatio: 'hero-sidebar',
    previewWireframe: [
      { id: 1, label: '#01 Hero Work', flex: 'h-full w-2/3' },
      { id: 2, label: '#02 Monitor A', flex: 'h-1/3 w-1/3' },
      { id: 3, label: '#03 Monitor B', flex: 'h-1/3 w-1/3' },
      { id: 4, label: '#04 Monitor C', flex: 'h-1/3 w-1/3' },
    ],
  },
  {
    id: '4-columns',
    name: '4-Columns',
    badge: 'PILLARS',
    category: 'quad',
    description: 'Four vertical strip columns for parallel service streams.',
    paneCount: 4,
    shortcut: 'Ctrl+4',
    tags: ['Columns', '4-Pillars', 'Services'],
    recommendedRatio: 'equal',
    previewWireframe: [
      { id: 1, label: '#01 Svc 1', flex: 'h-full w-1/4' },
      { id: 2, label: '#02 Svc 2', flex: 'h-full w-1/4' },
      { id: 3, label: '#03 Svc 3', flex: 'h-full w-1/4' },
      { id: 4, label: '#04 Svc 4', flex: 'h-full w-1/4' },
    ],
  },
  {
    id: '3x3',
    name: '6-Matrix 2×3',
    badge: 'DENSE SWARM',
    category: 'hexa',
    description: '6 equal panes arranged in 2 rows of 3 columns.',
    paneCount: 6,
    shortcut: '6',
    tags: ['Matrix', '2x3', 'Cluster'],
    recommendedRatio: 'equal',
    previewWireframe: [
      { id: 1, label: '#01', flex: 'h-1/2 w-1/3' },
      { id: 2, label: '#02', flex: 'h-1/2 w-1/3' },
      { id: 3, label: '#03', flex: 'h-1/2 w-1/3' },
      { id: 4, label: '#04', flex: 'h-1/2 w-1/3' },
      { id: 5, label: '#05', flex: 'h-1/2 w-1/3' },
      { id: 6, label: '#06', flex: 'h-1/2 w-1/3' },
    ],
  },
  {
    id: '6-command',
    name: '6-Command 1+5',
    badge: 'COCKPIT',
    category: 'hexa',
    description: '1 Large Lead Orchestrator + 5 Satellite Agent cockpits.',
    paneCount: 6,
    shortcut: 'Alt+6',
    tags: ['Command', '1+5', 'Cockpit'],
    recommendedRatio: 'hero-sidebar',
    previewWireframe: [
      { id: 1, label: '#01 Command', flex: 'h-full w-1/2' },
      { id: 2, label: '#02 Sub 1', flex: 'h-1/3 w-1/4' },
      { id: 3, label: '#03 Sub 2', flex: 'h-1/3 w-1/4' },
      { id: 4, label: '#04 Sub 3', flex: 'h-1/3 w-1/4' },
      { id: 5, label: '#05 Sub 4', flex: 'h-1/3 w-1/4' },
      { id: 6, label: '#06 Sub 5', flex: 'h-1/3 w-1/4' },
    ],
  },
  {
    id: '8-fleet',
    name: '8-Fleet 2×4',
    badge: 'FLEET',
    category: 'octa',
    description: '8-terminal high-density fleet matrix for microservices.',
    paneCount: 8,
    shortcut: '8',
    tags: ['Fleet', '2x4', 'Microservices'],
    recommendedRatio: 'equal',
    previewWireframe: [
      { id: 1, label: '#01', flex: 'h-1/2 w-1/4' },
      { id: 2, label: '#02', flex: 'h-1/2 w-1/4' },
      { id: 3, label: '#03', flex: 'h-1/2 w-1/4' },
      { id: 4, label: '#04', flex: 'h-1/2 w-1/4' },
      { id: 5, label: '#05', flex: 'h-1/2 w-1/4' },
      { id: 6, label: '#06', flex: 'h-1/2 w-1/4' },
      { id: 7, label: '#07', flex: 'h-1/2 w-1/4' },
      { id: 8, label: '#08', flex: 'h-1/2 w-1/4' },
    ],
  },
  {
    id: '9-hivemind',
    name: '9-Hivemind 3×3',
    badge: 'HIVEMIND',
    category: 'matrix',
    description: '9-pane symmetric command grid for massive agent pods.',
    paneCount: 9,
    shortcut: '9',
    tags: ['Hivemind', '3x3', 'Grid'],
    recommendedRatio: 'equal',
    previewWireframe: [
      { id: 1, label: '#01', flex: 'h-1/3 w-1/3' },
      { id: 2, label: '#02', flex: 'h-1/3 w-1/3' },
      { id: 3, label: '#03', flex: 'h-1/3 w-1/3' },
      { id: 4, label: '#04', flex: 'h-1/3 w-1/3' },
      { id: 5, label: '#05', flex: 'h-1/3 w-1/3' },
      { id: 6, label: '#06', flex: 'h-1/3 w-1/3' },
      { id: 7, label: '#07', flex: 'h-1/3 w-1/3' },
      { id: 8, label: '#08', flex: 'h-1/3 w-1/3' },
      { id: 9, label: '#09', flex: 'h-1/3 w-1/3' },
    ],
  },
  {
    id: '16-godmode',
    name: '16-GodMode 4×4',
    badge: 'GODMODE',
    category: 'matrix',
    description: '16 GPU-accelerated terminals for maximum agent concurrency.',
    paneCount: 16,
    shortcut: '0',
    tags: ['GodMode', '4x4', 'Wall of Code'],
    recommendedRatio: 'equal',
    previewWireframe: [
      { id: 1, label: '#01', flex: 'h-1/4 w-1/4' },
      { id: 2, label: '#02', flex: 'h-1/4 w-1/4' },
      { id: 3, label: '#03', flex: 'h-1/4 w-1/4' },
      { id: 4, label: '#04', flex: 'h-1/4 w-1/4' },
      { id: 5, label: '#05', flex: 'h-1/4 w-1/4' },
      { id: 6, label: '#06', flex: 'h-1/4 w-1/4' },
      { id: 7, label: '#07', flex: 'h-1/4 w-1/4' },
      { id: 8, label: '#08', flex: 'h-1/4 w-1/4' },
      { id: 9, label: '#09', flex: 'h-1/4 w-1/4' },
      { id: 10, label: '#10', flex: 'h-1/4 w-1/4' },
      { id: 11, label: '#11', flex: 'h-1/4 w-1/4' },
      { id: 12, label: '#12', flex: 'h-1/4 w-1/4' },
      { id: 13, label: '#13', flex: 'h-1/4 w-1/4' },
      { id: 14, label: '#14', flex: 'h-1/4 w-1/4' },
      { id: 15, label: '#15', flex: 'h-1/4 w-1/4' },
      { id: 16, label: '#16', flex: 'h-1/4 w-1/4' },
    ],
  },
];

