export interface DemoAgent {
  id: string;
  name: string;
  provider: string;
  command: string;
  defaultModel: string;
  supportedModels: string[];
  description: string;
  badge: string;
  badgeColor: string;
  category: 'cloud' | 'local' | 'hybrid' | 'orchestrator' | 'shell';
  iconType: 'bot' | 'sparkles' | 'zap' | 'globe' | 'file-text' | 'code' | 'terminal' | 'cpu' | 'server' | 'layers' | 'shield';
  simulatedLogs: { bullet: string; bulletColor: string; text: string }[];
  statusText: string;
  installCommand?: string;
  docUrl?: string;
  isInstalled?: boolean;
}

export interface DemoRolePodAssignment {
  paneIndex: number;
  title: string;
  agentId: string;
  model?: string;
  cliArgs?: string[];
  initialPrompt?: string;
}

export interface DemoRolePod {
  id: string;
  name: string;
  description: string;
  paneCount: number;
  assignments: DemoRolePodAssignment[];
}

export const DEMO_AGENTS: DemoAgent[] = [
  {
    id: 'claude-code',
    name: 'Claude Code',
    provider: 'Anthropic',
    command: 'claude --dangerously-skip-permissions',
    defaultModel: 'claude-3-7-sonnet',
    supportedModels: ['claude-3-7-sonnet', 'claude-3-5-sonnet', 'claude-3-5-haiku', 'claude-3-opus'],
    description: 'Anthropic agentic CLI with deep codebase reasoning, autonomous edits, and bash execution.',
    badge: 'CLAUDE ACTIVE',
    badgeColor: 'bg-[#111111] text-[#d97706] border-[#d97706]/50',
    category: 'cloud',
    iconType: 'bot',
    statusText: 'Generating Rust PTY batching pipeline & AST syn analysis...',
    isInstalled: true,
    installCommand: 'npm install -g @anthropic-ai/claude-code',
    docUrl: 'https://docs.anthropic.com/en/docs/agents-and-tools/claude-code',
    simulatedLogs: [
      { bullet: '●', bulletColor: 'text-[#d97706]', text: 'Spawning Rust PTY subprocess (PID 49102)...' },
      { bullet: '✔', bulletColor: 'text-[#27c93f]', text: 'WebGL 2.0 context initialized at 60.0 FPS' },
      { bullet: '⚡', bulletColor: 'text-[#ffbd2e]', text: 'IPC buffer latency: 1.2ms [optimal]' },
      { bullet: '→', bulletColor: 'text-[#d97706]', text: 'Orchestrating 16-pane terminal grid loop...' },
    ],
  },
  {
    id: 'codex',
    name: 'OpenAI Codex',
    provider: 'OpenAI',
    command: 'codex --exec --turbo',
    defaultModel: 'o3-mini',
    supportedModels: ['o3-mini', 'o1', 'gpt-4o', 'gpt-4o-mini', 'gpt-4.5-preview'],
    description: 'OpenAI coding agent with o3-mini and gpt-4o automated task loops, test synthesis and bug pinpointing.',
    badge: 'CODEX ACTIVE',
    badgeColor: 'bg-[#111111] text-emerald-400 border-emerald-500/50',
    category: 'cloud',
    iconType: 'sparkles',
    statusText: 'Synthesizing automated verification test suite...',
    isInstalled: true,
    installCommand: 'npm install -g @openai/codex',
    docUrl: 'https://platform.openai.com/docs',
    simulatedLogs: [
      { bullet: '●', bulletColor: 'text-emerald-400', text: 'Initializing OpenAI Codex session (o3-mini)...' },
      { bullet: '⚡', bulletColor: 'text-[#ffbd2e]', text: 'Running test suite: 142/142 tests passing' },
      { bullet: '✔', bulletColor: 'text-[#27c93f]', text: 'Discovered zero memory leaks in WebGL buffer pipeline' },
      { bullet: '✔', bulletColor: 'text-[#27c93f]', text: 'Injected WebGL shader uniform bindings' },
    ],
  },
  {
    id: 'antigravity',
    name: 'Antigravity / Integrity',
    provider: 'Google DeepMind',
    command: 'agy run --swarm-mode',
    defaultModel: 'gemini-2.5-pro',
    supportedModels: ['gemini-2.5-pro', 'gemini-2.5-flash', 'gemini-2.0-flash-thinking'],
    description: 'Google DeepMind multi-agent coding framework & skill runner orchestrating subagents and MCP tools.',
    badge: 'ANTIGRAVITY',
    badgeColor: 'bg-[#111111] text-[#3b82f6] border-[#3b82f6]/50',
    category: 'orchestrator',
    iconType: 'zap',
    statusText: 'Orchestrating subagent fleet across terminal nodes...',
    isInstalled: true,
    installCommand: 'curl -fsSL https://antigravity.google.com/install.sh | sh',
    docUrl: 'https://deepmind.google/technologies/antigravity',
    simulatedLogs: [
      { bullet: '●', bulletColor: 'text-[#3b82f6]', text: 'Antigravity supervisor spawned 4 subagent workers' },
      { bullet: '⚡', bulletColor: 'text-[#ffbd2e]', text: 'Bound MCP tools: [kanban_sync, diff_viewer, pty_pipe]' },
      { bullet: '✔', bulletColor: 'text-[#27c93f]', text: 'AST analysis across 58 source files complete' },
      { bullet: '→', bulletColor: 'text-[#3b82f6]', text: 'Autonomous deployment verified with 0 dropped frames' },
    ],
  },
  {
    id: 'grok',
    name: 'Grok CLI',
    provider: 'xAI',
    command: 'grok-cli --fast',
    defaultModel: 'grok-2',
    supportedModels: ['grok-2', 'grok-2-mini', 'grok-code'],
    description: 'xAI real-time web-connected coding agent with lightning-fast token generation.',
    badge: 'GROK ACTIVE',
    badgeColor: 'bg-[#111111] text-[#8b5cf6] border-[#8b5cf6]/50',
    category: 'cloud',
    iconType: 'globe',
    statusText: 'Querying real-time web knowledge graph & code index...',
    isInstalled: false,
    installCommand: 'npm install -g @xai/grok-cli',
    docUrl: 'https://x.ai/api',
    simulatedLogs: [
      { bullet: '●', bulletColor: 'text-[#8b5cf6]', text: 'Connected to xAI real-time low-latency stream' },
      { bullet: '⚡', bulletColor: 'text-[#ffbd2e]', text: 'Generation speed: 124 tok/s' },
      { bullet: '✔', bulletColor: 'text-[#27c93f]', text: 'Up-to-date documentation resolved for Actix Web v4.9' },
    ],
  },
  {
    id: 'kimi',
    name: 'Kimi CLI',
    provider: 'Moonshot AI',
    command: 'kimi-cli --context-2m',
    defaultModel: 'kimi-k1.5',
    supportedModels: ['kimi-k1.5', 'moonshot-v1-128k'],
    description: 'Moonshot AI 2M token context repository analyzer for monolith codebases and whole-project ASTs.',
    badge: 'KIMI ACTIVE',
    badgeColor: 'bg-[#111111] text-[#06b6d4] border-[#06b6d4]/50',
    category: 'cloud',
    iconType: 'file-text',
    statusText: 'Ingesting 2,000,000 token whole-repo context window...',
    isInstalled: false,
    installCommand: 'pip install kimi-cli',
    docUrl: 'https://www.moonshot.cn',
    simulatedLogs: [
      { bullet: '●', bulletColor: 'text-[#06b6d4]', text: 'Loaded 420 source files into 2M token buffer' },
      { bullet: '⚡', bulletColor: 'text-[#ffbd2e]', text: 'Monolith dependency graph calculated in 320ms' },
      { bullet: '✔', bulletColor: 'text-[#27c93f]', text: 'Cross-module reference resolution verified' },
    ],
  },
  {
    id: 'qwen',
    name: 'Qwen Coder CLI',
    provider: 'Alibaba Cloud',
    command: 'qwen-coder --polyglot',
    defaultModel: 'qwen2.5-coder-32b',
    supportedModels: ['qwen2.5-coder-32b', 'qwen2.5-coder-7b'],
    description: 'Alibaba Cloud Qwen 2.5 Coder supporting 92+ programming languages with top coding benchmark scores.',
    badge: 'QWEN ACTIVE',
    badgeColor: 'bg-[#111111] text-[#6366f1] border-[#6366f1]/50',
    category: 'hybrid',
    iconType: 'code',
    statusText: 'Synthesizing polyglot Rust & TypeScript type contracts...',
    isInstalled: false,
    installCommand: 'pip install qwen-coder-cli',
    docUrl: 'https://github.com/QwenLM/Qwen2.5-Coder',
    simulatedLogs: [
      { bullet: '●', bulletColor: 'text-[#6366f1]', text: 'Qwen 2.5 Coder 32B initialized' },
      { bullet: '✔', bulletColor: 'text-[#27c93f]', text: 'Polyglot verification: 92 languages supported' },
      { bullet: '⚡', bulletColor: 'text-[#ffbd2e]', text: 'Type contract synchronization: 0 type errors' },
    ],
  },
  {
    id: 'aider',
    name: 'Aider Pair Programmer',
    provider: 'Open Source',
    command: 'aider --auto-commits',
    defaultModel: 'claude-3-7-sonnet',
    supportedModels: ['claude-3-7-sonnet', 'deepseek-r1', 'gpt-4o', 'gemini-2.5-pro'],
    description: 'Git-aware terminal pair programmer with automatic commits, AST repo maps, and tree-sitter indexing.',
    badge: 'AIDER ACTIVE',
    badgeColor: 'bg-[#111111] text-[#ec4899] border-[#ec4899]/50',
    category: 'hybrid',
    iconType: 'terminal',
    statusText: 'Compiling architectural dark surface tokens & staging git commits...',
    isInstalled: true,
    installCommand: 'pip install aider-chat',
    docUrl: 'https://aider.chat',
    simulatedLogs: [
      { bullet: '●', bulletColor: 'text-[#ec4899]', text: 'AST parser analyzed 14 source files' },
      { bullet: '✔', bulletColor: 'text-[#27c93f]', text: 'Refactored architectural dark surface tokens' },
      { bullet: '✔', bulletColor: 'text-[#27c93f]', text: 'Ticker continuous marquee sync confirmed' },
      { bullet: '⚡', bulletColor: 'text-[#ffbd2e]', text: 'Staging git commit: feat(hero): architectural grid' },
    ],
  },
  {
    id: 'openhands',
    name: 'OpenHands',
    provider: 'All-Hands-AI',
    command: 'openhands --sandbox docker',
    defaultModel: 'claude-3-7-sonnet',
    supportedModels: ['claude-3-7-sonnet', 'gpt-4o'],
    description: 'Autonomous AI software developer agent in Docker container sandbox executing end-to-end tasks.',
    badge: 'OPENHANDS',
    badgeColor: 'bg-[#111111] text-[#f97316] border-[#f97316]/50',
    category: 'orchestrator',
    iconType: 'cpu',
    statusText: 'Spinning up containerized Docker runtime sandbox...',
    isInstalled: false,
    installCommand: 'pip install openhands-ai',
    docUrl: 'https://github.com/All-Hands-AI/OpenHands',
    simulatedLogs: [
      { bullet: '●', bulletColor: 'text-[#f97316]', text: 'Docker sandbox container spawned (alpine-node-rust)' },
      { bullet: '⚡', bulletColor: 'text-[#ffbd2e]', text: 'Executing test harness in isolated network namespace' },
      { bullet: '✔', bulletColor: 'text-[#27c93f]', text: 'Integration tests passed with 100% isolation' },
    ],
  },
  {
    id: 'ollama',
    name: 'Ollama (Local LLM)',
    provider: 'Local LLM',
    command: 'ollama run deepseek-r1:32b',
    defaultModel: 'deepseek-r1:32b',
    supportedModels: ['deepseek-r1:32b', 'deepseek-r1:8b', 'qwen2.5-coder:32b', 'qwen2.5-coder:7b', 'llama3.3:70b', 'codestral'],
    description: '100% air-gapped local model runner for DeepSeek-R1, Qwen, and Llama with zero network egress.',
    badge: 'OFFLINE OLLAMA',
    badgeColor: 'bg-[#111111] text-[#14b8a6] border-[#14b8a6]/50',
    category: 'local',
    iconType: 'server',
    statusText: 'Executing 100% air-gapped local inference on Apple Silicon / CUDA...',
    isInstalled: true,
    installCommand: 'brew install ollama',
    docUrl: 'https://ollama.com',
    simulatedLogs: [
      { bullet: '●', bulletColor: 'text-[#14b8a6]', text: 'DeepSeek-R1 32B loaded in unified VRAM (18.4 GB)' },
      { bullet: '⚡', bulletColor: 'text-[#ffbd2e]', text: 'Tool call: kanban_get_workspace_context()' },
      { bullet: '✔', bulletColor: 'text-[#27c93f]', text: '0ms network egress · 100% air-gapped privacy' },
      { bullet: '✔', bulletColor: 'text-[#27c93f]', text: 'AST symbols mapped into local state cache' },
    ],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek CLI',
    provider: 'DeepSeek',
    command: 'deepseek-cli run --reasoning',
    defaultModel: 'deepseek-r1',
    supportedModels: ['deepseek-r1', 'deepseek-chat', 'deepseek-coder'],
    description: 'DeepSeek reasoning & code intelligence CLI with deep chain-of-thought mathematical analysis.',
    badge: 'DEEPSEEK R1',
    badgeColor: 'bg-[#111111] text-[#38bdf8] border-[#38bdf8]/50',
    category: 'cloud',
    iconType: 'bot',
    statusText: 'Running DeepSeek-R1 chain-of-thought mathematical verification...',
    isInstalled: true,
    installCommand: 'npm install -g @deepseek/cli',
    docUrl: 'https://deepseek.com',
    simulatedLogs: [
      { bullet: '●', bulletColor: 'text-[#38bdf8]', text: 'DeepSeek-R1 chain-of-thought engine initialized' },
      { bullet: '⚡', bulletColor: 'text-[#ffbd2e]', text: 'CoT reasoning steps: 8 thought passes executed' },
      { bullet: '✔', bulletColor: 'text-[#27c93f]', text: 'Optimal algorithmic complexity verified: O(N log N)' },
      { bullet: '✔', bulletColor: 'text-[#27c93f]', text: 'Emitted verified Rust lifetime borrow check rules' },
    ],
  },
  {
    id: 'gemini',
    name: 'Gemini CLI',
    provider: 'Google AI',
    command: 'gemini --developer-mode',
    defaultModel: 'gemini-2.5-pro',
    supportedModels: ['gemini-2.5-pro', 'gemini-2.5-flash', 'gemini-1.5-pro'],
    description: 'Google Gemini 2.5 Pro multimodal developer assistant with 1M+ context window and fast reasoning.',
    badge: 'GEMINI 2.5',
    badgeColor: 'bg-[#111111] text-[#2563eb] border-[#2563eb]/50',
    category: 'cloud',
    iconType: 'zap',
    statusText: 'Processing multimodal developer inputs with 1M token context...',
    isInstalled: false,
    installCommand: 'npm install -g @google/gemini-cli',
    docUrl: 'https://ai.google.dev',
    simulatedLogs: [
      { bullet: '●', bulletColor: 'text-[#2563eb]', text: 'Gemini 2.5 Pro developer session mounted' },
      { bullet: '⚡', bulletColor: 'text-[#ffbd2e]', text: 'Context window utilization: 142k / 1,000k' },
      { bullet: '✔', bulletColor: 'text-[#27c93f]', text: 'Multimodal schema inference succeeded' },
    ],
  },
  {
    id: 'goose',
    name: 'Goose',
    provider: 'Block',
    command: 'goose session',
    defaultModel: 'claude-3-7-sonnet',
    supportedModels: ['claude-3-7-sonnet', 'gpt-4o', 'databricks-dbrx'],
    description: 'Extensible open-source AI agent by Block that automates engineering tasks through tool extensions.',
    badge: 'GOOSE ACTIVE',
    badgeColor: 'bg-[#111111] text-[#f59e0b] border-[#f59e0b]/50',
    category: 'orchestrator',
    iconType: 'layers',
    statusText: 'Executing automated tool extensions & engineering workflows...',
    isInstalled: false,
    installCommand: 'brew install block/goose/goose',
    docUrl: 'https://block.github.io/goose/',
    simulatedLogs: [
      { bullet: '●', bulletColor: 'text-[#f59e0b]', text: 'Goose extension toolchain loaded (6 extensions)' },
      { bullet: '⚡', bulletColor: 'text-[#ffbd2e]', text: 'Automated GitHub pull request draft generated' },
      { bullet: '✔', bulletColor: 'text-[#27c93f]', text: 'Linter and compiler diagnostics resolved' },
    ],
  },
  {
    id: 'cline',
    name: 'Cline CLI',
    provider: 'Cline',
    command: 'cline --auto-approve',
    defaultModel: 'claude-3-7-sonnet',
    supportedModels: ['claude-3-7-sonnet', 'gpt-4o', 'deepseek-r1'],
    description: 'Autonomous coding agent CLI with tool calling and human-in-the-loop approvals.',
    badge: 'CLINE ACTIVE',
    badgeColor: 'bg-[#111111] text-[#10b981] border-[#10b981]/50',
    category: 'cloud',
    iconType: 'bot',
    statusText: 'Running interactive tool calls with granular permissions...',
    isInstalled: false,
    installCommand: 'npm install -g cline-cli',
    docUrl: 'https://github.com/cline/cline',
    simulatedLogs: [
      { bullet: '●', bulletColor: 'text-[#10b981]', text: 'Cline tool execution engine connected' },
      { bullet: '⚡', bulletColor: 'text-[#ffbd2e]', text: 'Executing write_to_file with atomic rollback' },
      { bullet: '✔', bulletColor: 'text-[#27c93f]', text: 'File changes verified against linter' },
    ],
  },
  {
    id: 'shell',
    name: 'Native Shell (Zsh/Bash)',
    provider: 'System',
    command: 'zsh -l',
    defaultModel: 'zsh',
    supportedModels: [],
    description: 'Standard OS shell terminal with environment variables, PTY control, and fast execution.',
    badge: 'RAW SHELL',
    badgeColor: 'bg-[#111111] text-[#71717a] border-[#71717a]/50',
    category: 'shell',
    iconType: 'terminal',
    statusText: 'Native OS terminal session ready for shell commands.',
    isInstalled: true,
    docUrl: 'https://vibegrid.dev',
    simulatedLogs: [
      { bullet: '➜', bulletColor: 'text-[#71717a]', text: 'Zsh 5.9 (x86_64-apple-darwin23.0)' },
      { bullet: '✔', bulletColor: 'text-[#27c93f]', text: 'Interactive PTY initialized (/dev/ttys004)' },
      { bullet: '⚡', bulletColor: 'text-[#ffbd2e]', text: 'Sub-1ms keystroke roundtrip latency' },
    ],
  },
];

export const HETEROGENEOUS_ROLE_PODS: DemoRolePod[] = [
  {
    id: 'feature-team-4',
    name: 'Autonomous Feature Pod (4-Pane Quad)',
    description: '1 Architect (Claude) + 1 Refactorer (Aider) + 1 Local Explainer (Ollama) + 1 Dev Server',
    paneCount: 4,
    assignments: [
      { paneIndex: 0, title: 'Claude Code (Architect)', agentId: 'claude-code', model: 'claude-3-7-sonnet', initialPrompt: 'Analyze project structure and prepare implementation plan.' },
      { paneIndex: 1, title: 'Aider (Refactorer)', agentId: 'aider', model: 'claude-3-7-sonnet', cliArgs: ['--auto-commits'] },
      { paneIndex: 2, title: 'Ollama (DeepSeek R1)', agentId: 'ollama', model: 'deepseek-r1:32b' },
      { paneIndex: 3, title: 'Dev Server', agentId: 'shell' },
    ],
  },
  {
    id: 'pair-coder-3',
    name: 'AI Pair Programmer (3-Pane)',
    description: '1 Main Orchestrator + 1 Test Runner + 1 Log Watcher',
    paneCount: 3,
    assignments: [
      { paneIndex: 0, title: 'Claude Architect', agentId: 'claude-code', model: 'claude-3-7-sonnet', cliArgs: ['--dangerously-skip-permissions'] },
      { paneIndex: 1, title: 'Aider Pair', agentId: 'aider', model: 'claude-3-7-sonnet', cliArgs: ['--auto-commits'] },
      { paneIndex: 2, title: 'Test Watcher', agentId: 'shell' },
    ],
  },
  {
    id: 'privacy-local-4',
    name: 'Air-Gapped Privacy Swarm (4-Pane Local)',
    description: '4 Local Ollama instances running DeepSeek-R1 and Qwen Coder with 0 bytes cloud egress',
    paneCount: 4,
    assignments: [
      { paneIndex: 0, title: 'DeepSeek R1 Local', agentId: 'ollama', model: 'deepseek-r1:32b' },
      { paneIndex: 1, title: 'Qwen Coder 32B', agentId: 'ollama', model: 'qwen2.5-coder:32b' },
      { paneIndex: 2, title: 'Llama 3.3 70B', agentId: 'ollama', model: 'llama3.3:70b' },
      { paneIndex: 3, title: 'Local Terminal', agentId: 'shell' },
    ],
  },
  {
    id: 'fullstack-swarm-6',
    name: 'Full-Stack 6-Agent Swarm (6-Pane)',
    description: 'Claude Code, Codex, Antigravity, Aider, Ollama, and DeepSeek running in synchronized cluster',
    paneCount: 6,
    assignments: [
      { paneIndex: 0, title: 'Claude Lead Architect', agentId: 'claude-code', model: 'claude-3-7-sonnet' },
      { paneIndex: 1, title: 'Codex Unit Tester', agentId: 'codex', model: 'o3-mini' },
      { paneIndex: 2, title: 'Antigravity Supervisor', agentId: 'antigravity', model: 'gemini-2.5-pro' },
      { paneIndex: 3, title: 'Aider Git Committer', agentId: 'aider', model: 'claude-3-7-sonnet' },
      { paneIndex: 4, title: 'DeepSeek Reasoning', agentId: 'deepseek', model: 'deepseek-r1' },
      { paneIndex: 5, title: 'Ollama Privacy Node', agentId: 'ollama', model: 'deepseek-r1:32b' },
    ],
  },
];
